// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Z_cgc8c4vNP3GDpJs7lICTydRWFBlso',
    appId: '1:829113228309:web:bd3564e9953e58663d421c',
    messagingSenderId: '829113228309',
    projectId: 'myapp-8c478',
    authDomain: 'myapp-8c478.firebaseapp.com',
    storageBucket: 'myapp-8c478.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoiyud1zHi8wxBYADkl8My-Qh6_YXBzvQ',
    appId: '1:829113228309:android:8575594fb9efab6f3d421c',
    messagingSenderId: '829113228309',
    projectId: 'myapp-8c478',
    storageBucket: 'myapp-8c478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS0CK4bG79c0Q0Th7BH6-Uq740inPy97k',
    appId: '1:829113228309:ios:5642dd5413ba05103d421c',
    messagingSenderId: '829113228309',
    projectId: 'myapp-8c478',
    storageBucket: 'myapp-8c478.appspot.com',
    androidClientId: '829113228309-5ejd7ttq4luo86a9d6l4gpi1skdonci0.apps.googleusercontent.com',
    iosClientId: '829113228309-pb3m5jimu744vqh1tc3j1hp813vt4ta5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS0CK4bG79c0Q0Th7BH6-Uq740inPy97k',
    appId: '1:829113228309:ios:5642dd5413ba05103d421c',
    messagingSenderId: '829113228309',
    projectId: 'myapp-8c478',
    storageBucket: 'myapp-8c478.appspot.com',
    androidClientId: '829113228309-5ejd7ttq4luo86a9d6l4gpi1skdonci0.apps.googleusercontent.com',
    iosClientId: '829113228309-pb3m5jimu744vqh1tc3j1hp813vt4ta5.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
